version: '3.8'

services:
  php:
    image: php:8.4-apache
    container_name: Bo_m9_php
    ports:
      - "80:80"
    volumes:
      - './:/var/www/html'
      
  Bo_m9_jesper:
    image: mysql:latest
    container_name: Bo_m9_jesper
    environment:
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
    ports:
      - 3356:3306
    volumes:
    - ./docker/sql/:/docker-entrypoint-initdb.d
   

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: Bo_m9_phpmyadmin
    ports:
      - "8805:80"
    environment:
      PMA_HOST: '${DB_HOST}'
      PMA_USER: '${DB_USERNAME}'
      PMA_PASSWORD: '${DB_PASSWORD}'
    depends_on:
      - Bo_m9_jesper